spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id: api-1
        uri: lb://Welcome-Order
        predicates: 
          - Path=/order/**
      - id: api-2
        uri: lb://Greet-Service
        predicates: 
          - Path=/payment/**
      - id: api-3
        uri: lb://Login-Service
        predicates: 
          - Path=/login/**
server:
  port: 3333